fashion_shop.MVC/Models/Components/CategoryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fashion_shop.Core.DTOs.Requests.Admin;
using fashion_shop.Core.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace fashion_shop.MVC.Models.Components;

public class CategoryViewComponent : ViewComponent
{
    private readonly ICategoryService _categoryService;

    public CategoryViewComponent(ICategoryService categoryService)
    {
        _categoryService = categoryService ?? throw new ArgumentNullException(nameof(categoryService));
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var categoryGetParameter = new GetCategoryRequest();

        var categories = (await _categoryService.GetListAsync(categoryGetParameter)).Data.ToList();

        return View(categories);
    }
}

fashion_shop.MVC/Models/Components/FooterViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fashion_shop.Core.Common;
using fashion_shop.Core.DTOs.Responses.User;
using fashion_shop.Core.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace fashion_shop.MVC.Models.Components;

public class FooterViewComponent : ViewComponent
{
    private readonly ISettingService _settingService;

    public FooterViewComponent(ISettingService settingService)
    {
        _settingService = settingService ?? throw new ArgumentNullException(nameof(settingService));
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        ViewBag.BasicInfo = await _settingService.GetSettingAsync<BasicInfoSettingResponse>(SettingPrefixConstants.BasicInfoPrefix);

        return View();
    }
}

fashion_shop.MVC/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Text.Json;
using System.Threading.Tasks;
using fashion_shop.Core.Common;
using fashion_shop.Core.DTOs.Responses.User;
using fashion_shop.Core.Entities;
using fashion_shop.Core.Interfaces.Repositories;
using fashion_shop.Core.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace fashion_shop.MVC.Controllers;

[Route("cart")]
[Authorize]
public class CartController : Controller
{
    public class CartItem
    {
        public int ProductItemId { get; set; }
        public int Quantity { get; set; }
    }

    private readonly ILogger<CartController> _logger;
    private readonly SignInManager<User> _signInManager;
    private readonly UserManager<User> _userManager;
    private readonly ICartService _cartService;
    private readonly IProductService _productService;
    private readonly ISettingService _settingService;

    public CartController(
        ILogger<CartController> logger,
        SignInManager<User> signInManager,
        ICartService cartService,
        IProductService productService,
        UserManager<User> userManager,
        ISettingService settingService)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _signInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
        _cartService = cartService ?? throw new ArgumentNullException(nameof(cartService));
        _productService = productService ?? throw new ArgumentNullException(nameof(productService));
        _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        _settingService = settingService ?? throw new ArgumentNullException(nameof(settingService));
    }

    [HttpGet("index")]
    public async Task<IActionResult> Index()
    {
        var cart = GetCart();

        var cartItems = cart.ToDictionary(item => item.ProductItemId, item => item.Quantity);

        var cartItemData = await _cartService.GetListAsync(cartItems);

        ViewBag.CartItems = cartItemData;

        return View();
    }

    [HttpGet("add-to-cart")]
    public async Task<IActionResult> AddToCart(int productItemId)
    {
        var cart = GetCart();

        // check exist product
        var existingItem = cart?.FirstOrDefault(c => c.ProductItemId == productItemId);

        if (await _cartService.CheckProductExistByProductItemIdAsync(productItemId) is false)
        {
            return NotFound();
        }

        if (existingItem == null)
        {
            cart?.Add(new CartItem { ProductItemId = productItemId, Quantity = 1 });
        }

        // Update Cart
        var cartData = JsonSerializer.Serialize(cart);

        Response.Cookies.Append(GetCartId(), cartData, new CookieOptions
        {
            HttpOnly = true,
            Secure = false,
            SameSite = SameSiteMode.Lax,
            Expires = DateTimeOffset.UtcNow.AddDays(30)
        });

        return Ok(new { message = "Đã thêm sản phẩm vào giỏ hàng!" });
    }

    [HttpDelete("remove-in-cart")]
    public IActionResult RemoveInCart(int productItemId)
    {
        var cart = GetCart();

        // check exist product
        var existingItem = cart?.FirstOrDefault(c => c.ProductItemId == productItemId);

        if (existingItem is not null)
        {
            cart?.Remove(existingItem);
        }

        var cartData = JsonSerializer.Serialize(cart);

        Response.Cookies.Append(GetCartId(), cartData, new CookieOptions
        {
            HttpOnly = true,
            Secure = false,
            SameSite = SameSiteMode.Lax,
            Expires = DateTimeOffset.UtcNow.AddDays(30)
        });

        return Ok(new { message = "Đã xoá sản phẩm vào giỏ hàng!" });
    }

    [HttpGet("checkout")]
    public async Task<IActionResult> Checkout()
    {
        var cart = GetCart();

        var cartItems = cart.ToDictionary(item => item.ProductItemId, item => item.Quantity);

        var cartItemData = await _cartService.GetListAsync(cartItems);

        var user = await _userManager.GetUserAsync(User);

        ViewBag.CartItems = cartItemData;
        ViewBag.UserProfile = user;
        ViewBag.BasicInfo = await _settingService.GetSettingAsync<BasicInfoSettingResponse>(SettingPrefixConstants.BasicInfoPrefix);

        return View();
    }

    [HttpPost("checkout-cart")]
    public async Task<IActionResult> CheckoutCart()
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

        var cartId = $"Cart_{userId}";

        var cartCookie = Request.Cookies[cartId];

        if (userId == null)
        {
            return BadRequest("Not found user");
        }

        if (string.IsNullOrEmpty(cartCookie))
        {
            return BadRequest("Wrong Cookie");
        }

        var cart = JsonSerializer.Deserialize<List<CartItem>>(cartCookie);

        if (cart?.Count > 0)
        {
            var resp = await _cartService.CheckoutCartAsync(Int32.Parse(userId), cart.ToDictionary(item => item.ProductItemId, item => item.Quantity));

            if (resp)
            {
                Response.Cookies.Append(cartId, JsonSerializer.Serialize(new List<CartItem>()), new CookieOptions
                {
                    HttpOnly = true,
                    Secure = false,
                    SameSite = SameSiteMode.Lax,
                    Expires = DateTimeOffset.UtcNow.AddDays(30)
                });

                return Ok();
            }
        }

        return BadRequest("Cart empty");
    }


    [HttpGet("success-checkout")]
    public IActionResult SuccessCheckout()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View("Error!");
    }

    private List<CartItem> GetCart()
    {
        var cartId = GetCartId();

        var cartCookie = Request.Cookies[cartId];

        var cart = new List<CartItem>();

        if (!string.IsNullOrEmpty(cartCookie))
        {
            cart = JsonSerializer.Deserialize<List<CartItem>>(cartCookie);
        }
        else
        {
            var cartData = JsonSerializer.Serialize(cart);

            Response.Cookies.Append(cartId, cartData, new CookieOptions
            {
                HttpOnly = true,
                Secure = false,
                SameSite = SameSiteMode.Lax,
                Expires = DateTimeOffset.UtcNow.AddDays(30)
            });
        }

        return cart ?? new List<CartItem>();
    }

    private string GetCartId()
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

        return $"Cart_{userId}";
    }
}

fashion_shop.MVC/Controllers/ShopController.cs
using fashion_shop.Core.Common;
using fashion_shop.Core.DTOs.Requests.Admin;
using fashion_shop.Core.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace fashion_shop.MVC.Controllers;

[Route("shop")]
public class ShopController : Controller
{
    private readonly ILogger<ShopController> _logger;
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;

    public class DetailViewModel
    {
        public ProductDto ProductDetail { get; set; } = null!;
    }

    public ShopController(
        ILogger<ShopController> logger,
        IProductService productService,
        ICategoryService categoryService)
    {
        _logger = logger;
        _productService = productService ?? throw new ArgumentNullException(nameof(productService));
        _categoryService = categoryService ?? throw new ArgumentNullException(nameof(categoryService));
    }

    [HttpGet("index")]
    public async Task<IActionResult> Index(GetProductRequest request)
    {
        // Category
        var categoryGetParameter = new GetCategoryRequest();

        var categories = (await _categoryService.GetListAsync(categoryGetParameter)).Data;

        request.Offset = request.Offset != PaginationConstant.PageSize ? request.Offset : 6;
        var paginationProducts = await _productService.GetListAsync(request);

        var products = paginationProducts.Data;

        ViewBag.Categories = categories;
        ViewBag.Products = products;
        ViewBag.Meta = new
        {
            CurrentPage = paginationProducts.CurrentPage,
            PageSize = paginationProducts.PageSize,
            Total = paginationProducts.Total,
            LastPage = paginationProducts.LastPage,
        };

        return View();
    }

    [HttpGet("detail/{slug}")]
    public async Task<IActionResult> Detail(string slug)
    {
        var product = await _productService.GetDetailBySlugAsync(slug);

        if (product is null)
        {
            return NotFound();
        }

        ViewBag.ProductDetail = product;

        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View("Error!");
    }
}

fashion_shop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Fashion shop</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">

    <meta name="keywords" content="Fashion shop">
    <meta name="description" content="Stylish - Shoes Online Store HTML Template">

    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/vendor.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" type="text/css" href="~/css/style.css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=Playfair+Display:ital,wght@0,900;1,900&family=Source+Sans+Pro:wght@400;600;700;900&display=swap"
        rel="stylesheet">
</head>

<body class="d-flex flex-column min-vh-100">
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol xmlns="http://www.w3.org/2000/svg" id="shopping-carriage" viewBox="0 0 24 24" fill="none">
            <path
                d="M5 22H19C20.103 22 21 21.103 21 20V9C21 8.73478 20.8946 8.48043 20.7071 8.29289C20.5196 8.10536 20.2652 8 20 8H17V7C17 4.243 14.757 2 12 2C9.243 2 7 4.243 7 7V8H4C3.73478 8 3.48043 8.10536 3.29289 8.29289C3.10536 8.48043 3 8.73478 3 9V20C3 21.103 3.897 22 5 22ZM9 7C9 5.346 10.346 4 12 4C13.654 4 15 5.346 15 7V8H9V7ZM5 10H7V12H9V10H15V12H17V10H19L19.002 20H5V10Z"
                fill="black" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="quick-view" viewBox="0 0 24 24">
            <path fill="currentColor"
                d="M10 18a7.952 7.952 0 0 0 4.897-1.688l4.396 4.396l1.414-1.414l-4.396-4.396A7.952 7.952 0 0 0 18 10c0-4.411-3.589-8-8-8s-8 3.589-8 8s3.589 8 8 8zm0-14c3.309 0 6 2.691 6 6s-2.691 6-6 6s-6-2.691-6-6s2.691-6 6-6z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="shopping-cart" viewBox="0 0 24 24" fill="none">
            <path
                d="M21 4H2V6H4.3L7.582 15.025C7.79362 15.6029 8.1773 16.1021 8.68134 16.4552C9.18539 16.8083 9.78556 16.9985 10.401 17H19V15H10.401C9.982 15 9.604 14.735 9.461 14.342L8.973 13H18.246C19.136 13 19.926 12.402 20.169 11.549L21.962 5.275C22.0039 5.12615 22.0109 4.96962 21.9823 4.81763C21.9537 4.66565 21.8904 4.52234 21.7973 4.39889C21.7041 4.27544 21.5837 4.1752 21.4454 4.106C21.3071 4.0368 21.1546 4.00053 21 4ZM18.246 11H8.246L6.428 6H19.675L18.246 11Z"
                fill="black" />
            <path
                d="M10.5 21C11.3284 21 12 20.3284 12 19.5C12 18.6716 11.3284 18 10.5 18C9.67157 18 9 18.6716 9 19.5C9 20.3284 9.67157 21 10.5 21Z"
                fill="black" />
            <path
                d="M16.5 21C17.3284 21 18 20.3284 18 19.5C18 18.6716 17.3284 18 16.5 18C15.6716 18 15 18.6716 15 19.5C15 20.3284 15.6716 21 16.5 21Z"
                fill="black" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="nav-icon" viewBox="0 0 16 16">
            <path
                d="M14 10.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0 0 1h7a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="close" viewBox="0 0 16 16">
            <path
                d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="navbar-icon" viewBox="0 0 16 16">
            <path
                d="M14 10.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0 0 1h7a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="plus" viewBox="0 0 24 24">
            <path fill="currentColor" d="M19 12.998h-6v6h-2v-6H5v-2h6v-6h2v6h6z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="minus" viewBox="0 0 24 24">
            <path fill="currentColor" d="M19 12.998H5v-2h14z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="dropdown" viewBox="0 0 24 24">
            <path fill="currentColor" d="m7 10l5 5l5-5H7Z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="user" viewBox="0 0 24 24">
            <path fill="currentColor"
                d="M12 2a5 5 0 1 0 5 5a5 5 0 0 0-5-5zm0 8a3 3 0 1 1 3-3a3 3 0 0 1-3 3zm9 11v-1a7 7 0 0 0-7-7h-4a7 7 0 0 0-7 7v1h2v-1a5 5 0 0 1 5-5h4a5 5 0 0 1 5 5v1z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="arrow-right" viewBox="0 0 24 24">
            <path fill="currentColor"
                d="M13.3 17.275q-.3-.3-.288-.725t.313-.725L16.15 13H5q-.425 0-.713-.288T4 12q0-.425.288-.713T5 11h11.15L13.3 8.15q-.3-.3-.3-.713t.3-.712q.3-.3.713-.3t.712.3L19.3 11.3q.15.15.213.325t.062.375q0 .2-.063.375t-.212.325l-4.6 4.6q-.275.275-.687.275t-.713-.3Z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="facebook" viewBox="0 0 24 24">
            <path fill="currentColor"
                d="M9.198 21.5h4v-8.01h3.604l.396-3.98h-4V7.5a1 1 0 0 1 1-1h3v-4h-3a5 5 0 0 0-5 5v2.01h-2l-.396 3.98h2.396v8.01Z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="twitter" viewBox="0 0 512 512">
            <path fill="currentColor"
                d="M496 109.5a201.8 201.8 0 0 1-56.55 15.3a97.51 97.51 0 0 0 43.33-53.6a197.74 197.74 0 0 1-62.56 23.5A99.14 99.14 0 0 0 348.31 64c-54.42 0-98.46 43.4-98.46 96.9a93.21 93.21 0 0 0 2.54 22.1a280.7 280.7 0 0 1-203-101.3A95.69 95.69 0 0 0 36 130.4c0 33.6 17.53 63.3 44 80.7A97.5 97.5 0 0 1 35.22 199v1.2c0 47 34 86.1 79 95a100.76 100.76 0 0 1-25.94 3.4a94.38 94.38 0 0 1-18.51-1.8c12.51 38.5 48.92 66.5 92.05 67.3A199.59 199.59 0 0 1 39.5 405.6a203 203 0 0 1-23.5-1.4A278.68 278.68 0 0 0 166.74 448c181.36 0 280.44-147.7 280.44-275.8c0-4.2-.11-8.4-.31-12.5A198.48 198.48 0 0 0 496 109.5Z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="youtube" viewBox="0 0 32 32">
            <path fill="currentColor"
                d="M29.41 9.26a3.5 3.5 0 0 0-2.47-2.47C24.76 6.2 16 6.2 16 6.2s-8.76 0-10.94.59a3.5 3.5 0 0 0-2.47 2.47A36.13 36.13 0 0 0 2 16a36.13 36.13 0 0 0 .59 6.74a3.5 3.5 0 0 0 2.47 2.47c2.18.59 10.94.59 10.94.59s8.76 0 10.94-.59a3.5 3.5 0 0 0 2.47-2.47A36.13 36.13 0 0 0 30 16a36.13 36.13 0 0 0-.59-6.74ZM13.2 20.2v-8.4l7.27 4.2Z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="instagram" viewBox="0 0 256 256">
            <path fill="currentColor"
                d="M128 80a48 48 0 1 0 48 48a48.05 48.05 0 0 0-48-48Zm0 80a32 32 0 1 1 32-32a32 32 0 0 1-32 32Zm48-136H80a56.06 56.06 0 0 0-56 56v96a56.06 56.06 0 0 0 56 56h96a56.06 56.06 0 0 0 56-56V80a56.06 56.06 0 0 0-56-56Zm40 152a40 40 0 0 1-40 40H80a40 40 0 0 1-40-40V80a40 40 0 0 1 40-40h96a40 40 0 0 1 40 40ZM192 76a12 12 0 1 1-12-12a12 12 0 0 1 12 12Z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="pinterest" viewBox="0 0 24 24">
            <path fill="currentColor"
                d="M9.04 21.54c.96.29 1.93.46 2.96.46a10 10 0 0 0 10-10A10 10 0 0 0 12 2A10 10 0 0 0 2 12c0 4.25 2.67 7.9 6.44 9.34c-.09-.78-.18-2.07 0-2.96l1.15-4.94s-.29-.58-.29-1.5c0-1.38.86-2.41 1.84-2.41c.86 0 1.26.63 1.26 1.44c0 .86-.57 2.09-.86 3.27c-.17.98.52 1.84 1.52 1.84c1.78 0 3.16-1.9 3.16-4.58c0-2.4-1.72-4.04-4.19-4.04c-2.82 0-4.48 2.1-4.48 4.31c0 .86.28 1.73.74 2.3c.09.06.09.14.06.29l-.29 1.09c0 .17-.11.23-.28.11c-1.28-.56-2.02-2.38-2.02-3.85c0-3.16 2.24-6.03 6.56-6.03c3.44 0 6.12 2.47 6.12 5.75c0 3.44-2.13 6.2-5.18 6.2c-.97 0-1.92-.52-2.26-1.13l-.67 2.37c-.23.86-.86 2.01-1.29 2.7v-.03Z" />
        </symbol>
        <symbol xmlns="http://www.w3.org/2000/svg" id="search" viewBox="0 0 24 24">
            <path fill="currentColor"
                d="M10 18a7.952 7.952 0 0 0 4.897-1.688l4.396 4.396l1.414-1.414l-4.396-4.396A7.952 7.952 0 0 0 18 10c0-4.411-3.589-8-8-8s-8 3.589-8 8s3.589 8 8 8zm0-14c3.309 0 6 2.691 6 6s-2.691 6-6 6s-6-2.691-6-6s2.691-6 6-6z" />
        </symbol>
    </svg>
    <!-- Loader 4 -->

    <div class="preloader"
        style="position: fixed;top:0;left:0;width: 100%;height: 100%;background-color: #fff;display: flex;align-items: center;justify-content: center;z-index: 9999;">
        <svg version="1.1" id="L4" width="100" height="100" xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 50 100"
            enable-background="new 0 0 0 0" xml:space="preserve">
            <circle fill="#111" stroke="none" cx="6" cy="50" r="6">
                <animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.1" />
            </circle>
            <circle fill="#111" stroke="none" cx="26" cy="50" r="6">
                <animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.2" />
            </circle>
            <circle fill="#111" stroke="none" cx="46" cy="50" r="6">
                <animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.3" />
            </circle>
        </svg>
    </div>

    <header id="header" class="site-header text-black">
        <nav id="header-nav" class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                    <h3>Fashion Shop</h3>
                </a>
                <button class="navbar-toggler d-flex d-lg-none order-3 border-0 p-1 ms-2" type="button"
                    data-bs-toggle="offcanvas" data-bs-target="#bdNavbar" aria-controls="bdNavbar" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <svg class="navbar-icon">
                        <use xlink:href="#navbar-icon"></use>
                    </svg>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="bdNavbar">
                    <div class="offcanvas-body">
                        <ul id="navbar" class="navbar-nav fw-bold justify-content-end align-items-center flex-grow-1">
                            <li class="nav-item dropdown">
                                <a class="nav-link me-5" asp-action="Index" asp-controller="Home">Trang chủ</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link me-5 active dropdown-toggle border-0" href="#"
                                    data-bs-toggle="dropdown" aria-expanded="false">Danh mục sản phẩm</a>
                                @await Component.InvokeAsync("Category")
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-5 text-center" asp-action="Index" asp-controller="Shop">Shop</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="user-items ps-0 ps-md-5">
                    <ul class="d-flex justify-content-end list-unstyled align-item-center m-0">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="pe-3">
                                <a asp-action="Index" asp-controller="Cart" class="border-0">
                                    <svg class="shopping-cart" width="24" height="24">
                                        <use xlink:href="#shopping-cart"></use>
                                    </svg>
                                </a>
                            </li>
                            <li class="pe-3">
                                <a asp-action="Index" asp-controller="Profile" class="border-0">
                                    <svg class="user" width="24" height="24">
                                        <use xlink:href="#user"></use>
                                    </svg>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="pe-3">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">
                                    <svg class="user" width="24" height="24">
                                        <use xlink:href="#user"></use>
                                    </svg>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container flex-grow-1">
        @RenderBody()
    </main>

    @await Component.InvokeAsync("Footer")

    <script src="~/js/jquery-1.11.0.min.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>